# Generated by Django 3.1.5 on 2021-01-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=64, verbose_name='사용자이메일')),
                ('user_nickname', models.CharField(max_length=64, verbose_name='사용자이메일')),
                ('user_pw', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
        ),
    ]
