# Generated by Django 3.1.5 on 2021-01-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(max_length=64, verbose_name='사용자 닉네임'),
        ),
    ]
