# Generated by Django 3.1.5 on 2021-01-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0003_auto_20210121_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='u_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
