# Generated by Django 3.1.5 on 2021-01-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinus_app', '0011_delete_joinus'),
        ('member_app', '0004_auto_20210122_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
