# Generated by Django 3.1.5 on 2021-01-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_app', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=64, unique=True, verbose_name='사용자 이메일')),
                ('user_nickname', models.CharField(max_length=64, unique=True, verbose_name='사용자 닉네임')),
                ('user_pw', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
        ),
    ]
