# Generated by Django 3.1.5 on 2021-01-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(verbose_name='가입자 id')),
                ('m_id', models.IntegerField(verbose_name='모임 id')),
                ('join_dttm', models.DateTimeField(auto_now_add=True, verbose_name='가입 시간')),
            ],
        ),
    ]
