# Generated by Django 3.1.5 on 2021-01-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinus_app', '0010_joinus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joinus',
        ),
    ]
