# Generated by Django 3.1.5 on 2021-01-22 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_app', '0006_user'),
        ('noticeboard_app', '0009_meetings'),
        ('joinus_app', '0011_delete_joinus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joinus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225, verbose_name='카테고리')),
                ('join_dttm', models.DateTimeField(auto_now_add=True, verbose_name='가입 시간')),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='noticeboard_app.meetings')),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='member_app.user')),
            ],
        ),
    ]
