# Generated by Django 3.1.5 on 2021-01-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225, verbose_name='카테고리')),
                ('title', models.CharField(max_length=225, verbose_name='타이틀')),
                ('body', models.TextField(verbose_name='상세내용')),
                ('manager_id', models.IntegerField(verbose_name='등록 유저')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='이미지파일')),
            ],
        ),
    ]
