# Generated by Django 3.1.5 on 2021-01-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard_app', '0002_meetings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
