# Generated by Django 3.1.5 on 2021-01-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard_app', '0003_delete_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meetings',
        ),
    ]
