# Generated by Django 3.1.5 on 2021-01-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joinus_app', '0013_delete_joinus'),
        ('noticeboard_app', '0009_meetings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meetings',
        ),
    ]
